### ISSUE TITLE
failed to initialize tmd

### ISSUE THREAD

**Issue by pcs3rd** [Cruel/freeshop-site#2]
whenever trying to install bigger games, ( 1gb range) the install fails and gives 0xE0E083EC, but it worked with small apps. I have tried on multiple networks with the same result.

**Comment by pcs3rd** [comment]
currently, I have manually deleted the ticket and am reinstalling the game am trying to redownload

**Comment by pcs3rd** [comment]
now getting failed to finalize content: 0xD8E08025

**Comment by XCalibruh** [comment]
change ur sd card, this happened to me. You need to buy a new one, (Most preferably SanDisk)

**Comment by ghost** [comment]
Please help, I have this problem, Freeshop WAS working, but I had no space left on my measly 4 GB micro SD card, so I bought a Sandisk Ultra 64 GB Micro SD XC card, and I'm having the same problem as him. I managed to download a demo, but attempting to download just about ANYTHING (I even tried something that was like 350 MB) I get that same error message as pcs3rd "Failed to finalize TMD". Also please reply soon, because I only have two weeks before I can't return my new Micro SD. (Edit: Nevermind, I bought the SD card for $13, to ship it back would be $8, so if I can't use it for my 3DS I'l just find something else to use it for)

**Comment by ghost** [comment]
For reference, my original Micro SD Card was a Toshiba 4 GB Micro SD HC Card. It came with my New 3DS when I got it off eBay July last year.

**Comment by ghost** [comment]
Also the normal eShop doesn't work either. When I tried to download a free game "Ironfall Invasion" it gave me the error code 007-7390. When Also with Freeshop, after more experimentation, it appears the download limit is about 300 MB without getting the "Failed to finalize TMD" error.
